"""REPORT mode pipeline.

Compiles notes from TUI tabs + memory/store.py SQLite into a structured
markdown pentest report.  Optionally converts to PDF via weasyprint (if
installed) or pandoc (detected via shutil.which).  Falls back to .md if
neither is available.

Output file: <output_dir>/<YYYY-MM-DD>-<engagement>.md

Usage:
    cfg = ReportConfig(
        db_path=Path("memory/memory.db"),
        notes={"recon": "...", "10.10.14.5": "..."},
        output_dir=Path("reports/"),
        engagement="htb-legacy",
        generate_pdf=True,
    )
    reporter = Reporter(cfg)
    md = reporter.compile()   # returns raw markdown string
    path = reporter.save()    # writes file(s), returns Path to .md
"""

from __future__ import annotations

import datetime
import shutil
import sqlite3
import subprocess
import tempfile
from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class ReportConfig:
    db_path: Path
    output_dir: Path
    engagement: str
    notes: dict = field(default_factory=dict)   # tab_id -> notes_md
    generate_pdf: bool = False
    date: str = field(default_factory=lambda: datetime.date.today().isoformat())


class Reporter:
    def __init__(self, cfg: ReportConfig) -> None:
        self.cfg = cfg
        self._md: str = ""

    # ------------------------------------------------------------------
    # Public
    # ------------------------------------------------------------------

    def compile(self) -> str:
        """Build the markdown report string from notes + SQLite."""
        sections: list[str] = []
        sections.append(self._section_header())
        sections.append(self._section_executive_summary())
        sections.append(self._section_hosts())
        sections.append(self._section_findings())
        sections.append(self._section_creds())
        sections.append(self._section_timeline())
        sections.append(self._section_notes())
        self._md = "\n\n".join(s for s in sections if s.strip())
        return self._md

    def save(self) -> Path:
        """Write .md (and optionally PDF) to output_dir. Returns .md path."""
        if not self._md:
            self.compile()
        self.cfg.output_dir.mkdir(parents=True, exist_ok=True)
        filename = f"{self.cfg.date}-{self.cfg.engagement}.md"
        md_path = self.cfg.output_dir / filename
        md_path.write_text(self._md, encoding="utf-8")

        if self.cfg.generate_pdf:
            self._maybe_export_pdf(md_path)

        return md_path

    # ------------------------------------------------------------------
    # PDF export (best-effort)
    # ------------------------------------------------------------------

    def _maybe_export_pdf(self, md_path: Path) -> None:
        """Try weasyprint then pandoc; silently skip if neither is available."""
        pdf_path = md_path.with_suffix(".pdf")

        if shutil.which("weasyprint"):
            # weasyprint reads HTML; convert md -> html first via stdlib
            try:
                import html
                html_content = "<html><body><pre>" + html.escape(self._md) + "</pre></body></html>"
                with tempfile.NamedTemporaryFile(suffix=".html", delete=False, mode="w") as f:
                    f.write(html_content)
                    html_path = f.name
                subprocess.run(
                    ["weasyprint", html_path, str(pdf_path)],
                    check=True, capture_output=True,
                )
            except Exception:
                pass
            return

        if shutil.which("pandoc"):
            try:
                subprocess.run(
                    ["pandoc", str(md_path), "-o", str(pdf_path), "--pdf-engine=xelatex"],
                    check=True, capture_output=True,
                )
            except Exception:
                pass
            return

        # Neither available - skip silently (md is still written).

    # ------------------------------------------------------------------
    # Section builders
    # ------------------------------------------------------------------

    def _section_header(self) -> str:
        return (
            f"# Pentest Report - {self.cfg.engagement}\n"
            f"**Date:** {self.cfg.date}  \n"
            f"**Generated by:** Bagley TUI REPORT mode\n"
        )

    def _section_executive_summary(self) -> str:
        lines = ["## Executive Summary", ""]
        counts = self._finding_counts()
        total = sum(counts.values())
        lines.append(
            f"Engagement **{self.cfg.engagement}** yielded **{total}** findings: "
            + ", ".join(f"{v} {k.upper()}" for k, v in counts.items() if v)
            + "."
        )
        lines.append("")
        return "\n".join(lines)

    def _section_hosts(self) -> str:
        rows = self._query(
            "SELECT ip, hostname, first_seen, notes_md FROM hosts ORDER BY ip"
        )
        if not rows:
            return ""
        lines = ["## Hosts", "", "| IP | Hostname | First Seen | Notes |",
                 "|---|---|---|---|"]
        for ip, hostname, first_seen, notes_md in rows:
            lines.append(f"| {ip} | {hostname or ''} | {first_seen or ''} | {_trunc(notes_md)} |")
        return "\n".join(lines)

    def _section_findings(self) -> str:
        rows = self._query(
            "SELECT severity, category, summary, cve, host FROM findings "
            "ORDER BY CASE severity "
            "WHEN 'critical' THEN 1 WHEN 'high' THEN 2 WHEN 'medium' THEN 3 ELSE 4 END"
        )
        if not rows:
            return ""
        lines = ["## Findings", "",
                 "| Severity | Category | Summary | CVE | Host |",
                 "|---|---|---|---|---|"]
        for severity, category, summary, cve, host in rows:
            lines.append(
                f"| {severity.upper()} | {category} | {summary} | {cve or '-'} | {host} |"
            )
        return "\n".join(lines)

    def _section_creds(self) -> str:
        rows = self._query(
            "SELECT host, service, username, credential, source, validated FROM creds ORDER BY host"
        )
        if not rows:
            return ""
        lines = ["## Credentials", "",
                 "| Host | Service | Username | Credential | Source | Validated |",
                 "|---|---|---|---|---|---|"]
        for host, service, username, credential, source, validated in rows:
            v = "yes" if validated else "no"
            lines.append(f"| {host} | {service} | {username} | {credential} | {source} | {v} |")
        return "\n".join(lines)

    def _section_timeline(self) -> str:
        rows = self._query(
            "SELECT ts, host, technique, tool, outcome, details FROM attempts ORDER BY ts"
        )
        if not rows:
            return ""
        lines = ["## Attack Timeline", "", "| Time | Host | Technique | Tool | Outcome |",
                 "|---|---|---|---|---|"]
        for ts, host, technique, tool, outcome, details in rows:
            lines.append(f"| {ts} | {host} | {technique} | {tool} | {outcome} |")
        return "\n".join(lines)

    def _section_notes(self) -> str:
        if not self.cfg.notes:
            return ""
        parts = ["## Operator Notes", ""]
        for tab_id, notes_md in self.cfg.notes.items():
            if notes_md and notes_md.strip():
                parts.append(f"### {tab_id}")
                parts.append(notes_md.strip())
                parts.append("")
        return "\n".join(parts)

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _query(self, sql: str) -> list[tuple]:
        try:
            conn = sqlite3.connect(self.cfg.db_path)
            try:
                return conn.execute(sql).fetchall()
            finally:
                conn.close()
        except Exception:
            return []

    def _finding_counts(self) -> dict:
        rows = self._query(
            "SELECT severity, COUNT(*) FROM findings GROUP BY severity"
        )
        counts: dict = {}
        for severity, count in rows:
            counts[severity.lower()] = count
        return counts


def _trunc(text: str, limit: int = 60) -> str:
    if not text:
        return ""
    text = text.replace("\n", " ").strip()
    return text[:limit] + "..." if len(text) > limit else text
